new.minBalance=10000.0
new.interestRate=2.70

standard.minBalance=7500.0
standard.interestRate=3.00

premium.minBalance=5000.0
premium.interestRate=3.50

privilege.minBalance=2500.0
privilege.interestRate=4.00